Firefly disable cmds
apollo-lhc/cm_mcu pull request #81
Opened 2020-11-14 07:12 UTC by fatimayousuf

Addresses issue #74 

We can run the command `ff_status` to read the status of all the fireflies. "0" means that we can read data off of the firefly. "1" means that we can not (See pg 53 of the manual).

Here is a picture of a sample output of the `ff_status` command:
<img width="600" alt="Screen Shot 2020-11-13 at 10 29 31 PM" src="https://user-images.githubusercontent.com/37788505/99141970-42107980-2605-11eb-90c0-90203893ab7e.png">

I also added functions to enable and disable the receivers of the fireflies. To test them, I looked at the power on the firefly over time on Grafana. The power dipped after disabling the receivers and went up again after enabling the receivers.

I used the given xml file to reformat the code. It seems like there is quite a big difference. I am not sure I did something wrong there. I can undo that formatting if necessary.

2020-11-15 15:57 UTC, pwittich commented
(I left this comment elsewhere, leave it here too) If you can revert the reformat of the code it will make the review easier, if that's not too much trouble. I can take care of the reformatting.

2020-11-19 15:09 UTC, pwittich requested changes
Looks good! Please see the comments above for a few minor change requests.

2020-11-19 15:09 UTC, pwittich commented on projects/cm_mcu/CommandLineTask.c
> +		copied += snprintf(m + copied, SCRATCH_SIZE - copied, "%s %02d\r\n", name, status);
I'm a bit concerned about buffer overflow here. can you take a look at the logic for e.g. `adc_ctl` and follow that to ensure that we do not overwrite the `m` output buffer? It uses a static variable in the loop to differentiate between the first and subsequent entry into the loop (`whichadc`) and uses that to keep track of where in the buffer we are. Also if you could put the printout into two column format (see `ff_ctl` as an example) it would be helpful.

2020-11-19 15:21 UTC, pwittich commented
closes #72 also

2020-11-19 15:22 UTC, pwittich commented
One additional comment, in #74 we said we wanted to disable the firefly transmitters and receivers by default on startup. Is this included in the code? I think we did not put it into the checklist so ...

2020-11-20 01:30 UTC, fatimayousuf commented
> One additional comment, in #74 we said we wanted to disable the firefly transmitters and receivers by default on startup. Is this included in the code? I think we did not put it into the checklist so ...

Yes, I turned off the receivers/transmitters in lines 441-443 of FireFlyTask.c

2020-11-20 03:42 UTC, pwittich commented
> closes #72 also

actually we list some additional registers in #72; can we add those to the `ff_status` command?

2020-11-21 23:34 UTC, merged